### ISSUE TITLE
Cannot reattach

### ISSUE THREAD

**Issue by thejmazz** [wallneradam/docker-coreos-toolbox-ubuntu#3]
Hey, cool script you got here. Found this repo after trying some things on my own; installed tmux inside a brand new ubuntu toolbox, detached, and was not able to get back in. `machinectl list` shows nothing as well. (I also tried `apt install -y systemd dbus` as per [this issue](https://github.com/systemd/systemd/issues/685)).

I thought perhaps your use of `toolbox tmux` and `toolbox tmux attach -t 0` might work (as oppsed to launched tmux from inside a toolbox shell as I was first doing), but I still cannot reattach:

```
Failed to allocate scope: Unit toolbox-ubuntu.scope already exists.
```

Also, I do not know how to use `nsenter` to "get back in" to the container. I am wondering if the `machinectl` issues are CoreOS specific.

Any ideas? Are you still using this without issue, on latest stable? (atm, 1745.7.0)

FWIW, I have found an [alternate solution](https://groups.google.com/forum/#!topic/coreos-dev/JAeABXnQzuE) which is to use statically built binaries (or AppImage's), and the following container linux config works:

```yaml
storage:
  files:
    - path: /opt/bin/neofetch
      filesystem: root
      mode: 0555
      contents:
        remote:
          url: https://github.com/dylanaraps/neofetch/releases/download/5.0.0/neofetch
          verification:
            hash:
              function: sha512
              sum: d17d1b541b5f55d6614e3cee07205a23059245343a1b8fdc76d4ecc9c6ba900445aa39d4a6be29f8771225b51e3c292c2d94cb03f17fa84278e4046fd8009ad8
    - path: /opt/installers/nvim.sh
      filesystem: root
      mode: 0544
      contents:
        inline: |
          #!/bin/bash

          cmd=$(command -v nvim)
          [ ! -z "$cmd" ] && echo "nvim already installed at $cmd" | systemd-cat && exit 0

          BASE_URL=https://github.com/neovim/neovim/releases/download
          VERSION=0.3.0

          wget --quiet $BASE_URL/v$VERSION/nvim.appimage
          chmod +x nvim.appimage
          # No FUSE, so need --appimage-extract
          ./nvim.appimage --appimage-extract > /dev/null 2>&1
          rm nvim.appimage
          mv squashfs-root /opt/nvim
          chmod 755 -R /opt/nvim
          ln -s /opt/nvim/usr/bin/nvim /opt/bin/nvim
      # TODO these minos installers can be generalized
    - path: /opt/installers/tmux.sh
      filesystem: root
      mode: 0544
      contents:
        inline: |
          #!/bin/bash

          cmd=$(command -v tmux)
          [ ! -z "$cmd" ] && echo "tmux already installed at $cmd" && exit 0

          PACKAGE=tmux-1.9a.tar.xz

          wget --quiet http://s.minos.io/archive/morpheus/x86_64/$PACKAGE
          tar -C /opt -xf $PACKAGE
          rm $PACKAGE
    - path: /opt/installers/htop.sh
      filesystem: root
      mode: 0544
      contents:
        inline: |
          #!/bin/bash

          cmd=$(command -v htop)
          [ ! -z "$cmd" ] && echo "htop already installed at $cmd" && exit 0

          PACKAGE=htop-1.0.3.tar.xz

          wget --quiet http://s.minos.io/archive/morpheus/x86_64/$PACKAGE
          tar -C /opt -xf $PACKAGE
          rm $PACKAGE

systemd:
  units:
    - name: install-scripts.service
      enabled: true
      contents: |
        [Unit]
        Description=idempotent scripts to install statically linked programs

        [Service]
        Type=oneshot
        ExecStart=/opt/installers/tmux.sh
        ExecStart=/opt/installers/nvim.sh
        ExecStart=/opt/installers/htop.sh

        [Install]
        WantedBy=multi-user.target
```

Which, just for fun :D, looks like:

![screenshot from 2018-07-03 18-55-18](https://user-images.githubusercontent.com/1270998/42248269-b28e7048-7ef2-11e8-9e68-b581158ed8b8.png)
